"""Runtime tests for skill execution handlers."""

from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path
from unittest.mock import patch

import yaml

from testpipe import bootstrap
from testpipe.cli.main import main
from testpipe.skills import SkillRunner
from testpipe.spec import EnvProfile


class SkillRuntimeTest(unittest.TestCase):
    def _run(self, cmd: list[str], cwd: str | None = None) -> None:
        subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)

    def _create_git_resource_repo(self, root: Path) -> tuple[str, str]:
        repo_dir = root / "onnx-layer"
        repo_dir.mkdir(parents=True, exist_ok=True)
        self._run(["git", "init"], cwd=str(repo_dir))
        self._run(["git", "config", "user.email", "test@example.com"], cwd=str(repo_dir))
        self._run(["git", "config", "user.name", "TestPipe"], cwd=str(repo_dir))
        resource_dir = repo_dir / "Abs_testcase_5a6b43" / "resources"
        resource_dir.mkdir(parents=True, exist_ok=True)
        (resource_dir / "Abs_testcase_5a6b43.onnx").write_text("fake onnx payload\n", encoding="utf-8")
        self._run(["git", "add", "."], cwd=str(repo_dir))
        self._run(["git", "commit", "-m", "init resource"], cwd=str(repo_dir))
        self._run(["git", "checkout", "-b", "Abs"], cwd=str(repo_dir))
        commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=str(repo_dir), check=True, capture_output=True, text=True).stdout.strip()
        return str(repo_dir), commit

    def _create_fake_atc_env(self, root: Path) -> str:
        bin_dir = root / "bin"
        bin_dir.mkdir(parents=True, exist_ok=True)
        atc_script = bin_dir / "atc"
        atc_script.write_text(
            "\n".join(
                [
                    "#!/usr/bin/env bash",
                    "set -euo pipefail",
                    "output=\"\"",
                    "model=\"\"",
                    "for arg in \"$@\"; do",
                    "  case \"$arg\" in",
                    "    --output=*) output=\"${arg#*=}\" ;;",
                    "    --model=*) model=\"${arg#*=}\" ;;",
                    "  esac",
                    "done",
                    "cp \"$model\" \"${output}.om\"",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        atc_script.chmod(0o755)
        env_script = root / "set_env.sh"
        env_script.write_text(f"#!/usr/bin/env bash\nexport PATH={bin_dir}:$PATH\n", encoding="utf-8")
        env_script.chmod(0o755)
        return str(env_script)

    def _onnx_case_document(self, *, repo: str, env_script: str, case_ids: list[str]) -> dict[str, object]:
        return {
            "pipeline": {
                "name": "OnnxGitAtcPipeline",
                "fetchModelNode": {
                    "repo": repo,
                    "branch": "Abs",
                    "path": "Abs_testcase_5a6b43",
                    "model_pattern": "*.onnx",
                },
                "compileModelNode": {
                    "env_script": env_script,
                    "soc_version": "Ascend310P3",
                },
            },
            "cases": [{"case_id": case_id} for case_id in case_ids],
        }

    def _write_case_file(self, root: Path, name: str, payload: dict[object, object]) -> Path:
        path = root / name
        path.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
        return path

    def test_case_generator_builds_case_spec_and_yaml(self) -> None:
        bootstrap()
        result = SkillRunner().run(
            "case-generator",
            {
                "pipeline": {
                    "name": "OnnxGitAtcPipeline",
                    "fetchModelNode": {"repo": "repo", "branch": "main", "path": "model"},
                    "compileModelNode": {"soc_version": "Ascend310P3", "env_script": "/tmp/set_env.sh"},
                },
                "cases": [
                    {
                        "case_id": "onnx_generated",
                        "description": "generated by skill",
                        "level": "P1",
                    }
                ],
            },
        )
        self.assertEqual(result["case_spec"]["pipeline"], "OnnxGitAtcPipeline")
        self.assertIn("pipeline:", result["yaml_case_draft"])

    def test_pipeline_generator_outputs_mermaid_and_draft_spec(self) -> None:
        bootstrap()
        result = SkillRunner().run(
            "pipeline-generator",
            {
                "pipeline_name": "GeneratedPipeline",
                "business_goal": "compile and transfer",
                "pipeline_inputs": ["resource_path"],
                "pipeline_outputs": ["remote_path"],
                "stages": [{"name": "prepare"}, {"name": "compile"}, {"name": "transfer"}],
                "required_ops": ["EnvCheck", "ATCCompile", "Transfer"],
            },
        )
        self.assertEqual(result["pipeline_spec"]["name"], "GeneratedPipeline")
        self.assertIn("flowchart LR", result["mermaid_graph"])
        self.assertIn("self.set_stage('prepare')", result["python_pipeline_draft"])
        self.assertIn("self.add_node(", result["python_pipeline_draft"])

    def test_test_op_generator_can_scaffold_files(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = SkillRunner().run(
                "test-op-generator",
                {
                    "op_name": "PathExistsCheck",
                    "business_goal": "check whether a path exists",
                    "inputs": [{"name": "target_path", "type": "artifact:path", "description": "path to inspect"}],
                    "outputs": [{"name": "path_exists", "type": "bool", "description": "path existence result"}],
                    "scaffold": {
                        "enabled": True,
                        "root_dir": tmp_dir,
                    },
                },
            )
            self.assertEqual(len(result["written_files"]), 4)
            self.assertTrue((Path(tmp_dir) / "ops" / "path_exists_check.py").exists())
            self.assertTrue((Path(tmp_dir) / "tests" / "test_path_exists_check.py").exists())
            self.assertTrue((Path(tmp_dir) / "docs" / "ops" / "path_exists_check.md").exists())

    def test_pipeline_generator_can_scaffold_files(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = SkillRunner().run(
                "pipeline-generator",
                {
                    "pipeline_name": "AutoCompilePipeline",
                    "business_goal": "fetch, compile, and transfer model",
                    "pipeline_inputs": ["resource_path"],
                    "pipeline_outputs": ["remote_path"],
                    "stages": [{"name": "prepare"}, {"name": "compile"}, {"name": "transfer"}],
                    "required_ops": ["ResourceFetch", "ATCCompile", "Transfer"],
                    "scaffold": {
                        "enabled": True,
                        "root_dir": tmp_dir,
                    },
                },
            )
            self.assertEqual(len(result["written_files"]), 3)
            self.assertTrue((Path(tmp_dir) / "pipelines" / "auto_compile_pipeline.py").exists())
            self.assertTrue((Path(tmp_dir) / "docs" / "pipelines" / "auto_compile_pipeline.mmd").exists())
            self.assertTrue((Path(tmp_dir) / "docs" / "pipelines" / "auto_compile_pipeline.pipeline.json").exists())

    def test_case_runner_can_execute_case(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            case_file = self._write_case_file(Path(tmp_dir), "onnx.yaml", self._onnx_case_document(repo=repo_dir, env_script=env_script, case_ids=["onnx_case"]))
            result = SkillRunner().run(
                "case-runner",
                {
                    "case_ref": str(case_file),
                    "output_dir": tmp_dir,
                    "execute": True,
                },
            )
            self.assertIsNotNone(result["result_location"])
            self.assertEqual(result["summary"]["status"], "passed")
            self.assertTrue((Path(result["result_location"]) / "summary.json").exists())

    def test_case_runner_can_execute_multi_case_file(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            case_file = self._write_case_file(
                Path(tmp_dir),
                "onnx_suite.yaml",
                self._onnx_case_document(repo=repo_dir, env_script=env_script, case_ids=["suite_a", "suite_b"]),
            )
            result = SkillRunner().run(
                "case-runner",
                {
                    "case_ref": str(case_file),
                    "output_dir": tmp_dir,
                    "execute": True,
                },
            )
            self.assertIsNone(result["result_location"])
            self.assertEqual(len(result["result_locations"]), 2)
            self.assertEqual(len(result["summaries"]), 2)
            self.assertTrue(all(item["status"] == "passed" for item in result["summaries"]))

    def test_case_runner_loads_env_profile_file(self) -> None:
        bootstrap()
        framework_config = {
            "testpipe": {
                "default_env": "local",
                "envs": {
                    "local": {"enabled": True, "host": {"mode": "local"}},
                    "remote_mock": {
                        "enabled": True,
                        "host": {
                            "mode": "docker",
                            "workdir": "/workspace/testpipe",
                            "docker_image": "testpipe:latest",
                        },
                        "device": {
                            "protocol": "ssh",
                            "host": "192.168.1.10",
                            "port": 22,
                            "user": "root",
                        },
                        "transport": {
                            "mode": "sftp",
                            "size_threshold_mb": 128,
                        },
                        "metadata": {
                            "profile_name": "remote_mock",
                        },
                    },
                },
            }
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            config_file = Path(tmp_dir) / "testpipe.config.yaml"
            config_file.write_text(yaml.safe_dump(framework_config, allow_unicode=True, sort_keys=False), encoding="utf-8")
            case_file = self._write_case_file(
                Path(tmp_dir),
                "onnx.yaml",
                {
                    "pipeline": {"name": "OnnxGitAtcPipeline"},
                    "cases": [
                        {
                            "case_id": "onnx_case",
                            "fetchModelNode": {"repo": "repo", "branch": "main", "path": "model"},
                            "compileModelNode": {"soc_version": "Ascend310P3"},
                        }
                    ],
                },
            )
            result = SkillRunner().run(
                "case-runner",
                {
                    "case_ref": str(case_file),
                    "output_dir": tmp_dir,
                    "framework_config": str(config_file),
                    "env_profile": "remote_mock",
                    "execute": False,
                },
            )
            self.assertEqual(result["run_plan_summary"]["env_profile"]["host"]["mode"], "docker")
            self.assertEqual(result["run_plan_summary"]["env_profile"]["device"]["host"], "192.168.1.10")
            self.assertIn("--env-profile", result["run_command"])

    def test_result_analyzer_reports_failure_root_cause(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            bad_case = {
                "test_case": {
                    "case_id": "bad_expect",
                    "name": "BadExpect",
                    "pipeline": "OnnxGitAtcPipeline",
                    "inputs_by_node": {
                        "fetchModelNode": {
                            "repo": repo_dir,
                            "branch": "Abs",
                            "path": "Abs_testcase_5a6b43",
                            "model_pattern": "*.onnx",
                        },
                        "compileModelNode": {
                            "env_script": env_script,
                            "soc_version": "Ascend310P3",
                            "output_name": "abs_model.om",
                        },
                    },
                    "expected": {"path_exists": False},
                }
            }
            case_file = Path(tmp_dir) / "bad_case.yaml"
            case_file.write_text(yaml.safe_dump(bad_case, allow_unicode=True, sort_keys=False), encoding="utf-8")
            run_result = SkillRunner().run(
                "case-runner",
                {
                    "case_ref": str(case_file),
                    "output_dir": tmp_dir,
                    "execute": True,
                },
            )
            summary_ref = Path(str(run_result["result_location"])) / "summary.json"
            analysis = SkillRunner().run("result-analyzer", {"summary_ref": str(summary_ref)})
            self.assertIn("path_exists expected", analysis["root_cause"])
            self.assertTrue(analysis["fix_suggestions"])

    def test_run_skill_cli_outputs_json(self) -> None:
        bootstrap()
        payload = {
            "pipeline": {
                "name": "OnnxGitAtcPipeline",
                "fetchModelNode": {"repo": "repo", "branch": "main", "path": "model"},
                "compileModelNode": {"soc_version": "Ascend310P3"},
            },
            "cases": [
                {
                    "case_id": "cli_generated",
                }
            ],
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            payload_file = Path(tmp_dir) / "generate_case.yaml"
            payload_file.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(["run-skill", "case-generator", str(payload_file), "--json"])
            self.assertEqual(exit_code, 0)
            result = json.loads(buffer.getvalue())
            self.assertEqual(result["case_spec"]["pipeline"], "OnnxGitAtcPipeline")

    def test_run_skill_cli_can_check_case(self) -> None:
        bootstrap()
        payload = {
            "pipeline_spec_ref": "OnnxGitAtcPipeline",
            "case_spec": {
                "name": "InlineCase",
                "case_id": "inline_case",
                "pipeline": "OnnxGitAtcPipeline",
                "inputs": {},
                "inputs_by_node": {
                    "fetchModelNode": {
                        "repo": "repo",
                        "branch": "main",
                        "path": "model",
                    },
                    "compileModelNode": {"soc_version": "Ascend310P3"},
                },
                "expected": {"path_exists": True},
            },
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            payload_file = Path(tmp_dir) / "check_case.yaml"
            payload_file.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(["run-skill", "case-checker", str(payload_file), "--json"])
            self.assertEqual(exit_code, 0)
            result = json.loads(buffer.getvalue())
            self.assertEqual(result["status"], "pass")

    def test_run_skill_cli_can_check_case_suite(self) -> None:
        bootstrap()
        payload = {
            "pipeline_spec_ref": "OnnxGitAtcPipeline",
            "case_spec": {
                "pipeline": {
                    "name": "OnnxGitAtcPipeline",
                },
                "cases": [
                    {
                        "case_id": "suite_a",
                        "fetchModelNode": {"repo": "repo_a", "branch": "main", "path": "model_a"},
                        "compileModelNode": {"soc_version": "Ascend310P3"},
                    },
                    {
                        "case_id": "suite_b",
                        "fetchModelNode": {"repo": "repo_b", "branch": "main", "path": "model_b"},
                        "compileModelNode": {"soc_version": "Ascend310P3"},
                    },
                ],
            },
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            payload_file = Path(tmp_dir) / "check_suite.yaml"
            payload_file.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(["run-skill", "case-checker", str(payload_file), "--json"])
            self.assertEqual(exit_code, 0)
            result = json.loads(buffer.getvalue())
            self.assertEqual(result["case_count"], 2)
            self.assertEqual(result["status"], "pass")

    def test_run_skill_cli_can_execute_case_runner_with_clean_json(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            case_file = self._write_case_file(Path(tmp_dir), "onnx.yaml", self._onnx_case_document(repo=repo_dir, env_script=env_script, case_ids=["onnx_case"]))
            payload = {
                "case_ref": str(case_file),
                "output_dir": tmp_dir,
                "execute": True,
            }
            payload_file = Path(tmp_dir) / "run_case.yaml"
            payload_file.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(["run-skill", "case-runner", str(payload_file), "--json"])
            self.assertEqual(exit_code, 0)
            result = json.loads(buffer.getvalue())
            self.assertEqual(result["summary"]["status"], "passed")
            self.assertTrue(result["execution_console_log"])

    def test_run_skill_cli_can_scaffold_pipeline_files(self) -> None:
        bootstrap()
        payload = {
            "pipeline_name": "ScaffoldPipeline",
            "business_goal": "generated pipeline",
            "pipeline_inputs": ["message"],
            "pipeline_outputs": ["echoed_message"],
            "stages": [{"name": "prepare"}, {"name": "execute"}],
            "required_ops": ["EnvCheck", "Echo"],
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            payload["scaffold"] = {
                "enabled": True,
                "root_dir": tmp_dir,
            }
            payload_file = Path(tmp_dir) / "generate_pipeline.yaml"
            payload_file.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(["run-skill", "pipeline-generator", str(payload_file), "--json"])
            self.assertEqual(exit_code, 0)
            result = json.loads(buffer.getvalue())
            self.assertTrue(result["written_files"])
            self.assertTrue((Path(tmp_dir) / "pipelines" / "scaffold_pipeline.py").exists())

    def test_run_cli_accepts_env_profile_file(self) -> None:
        bootstrap()
        framework_config = {
            "testpipe": {
                "default_env": "local",
                "envs": {
                    "local": {"enabled": True, "host": {"mode": "local"}},
                    "custom_local": {
                        "enabled": True,
                        "host": {
                            "mode": "local",
                        },
                        "transport": {
                            "mode": "local",
                            "size_threshold_mb": 64,
                        },
                        "metadata": {
                            "profile_name": "custom_local",
                        },
                    },
                },
            }
        }
        with tempfile.TemporaryDirectory() as tmp_dir:
            config_file = Path(tmp_dir) / "testpipe.config.yaml"
            config_file.write_text(yaml.safe_dump(framework_config, allow_unicode=True, sort_keys=False), encoding="utf-8")
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            case_file = self._write_case_file(Path(tmp_dir), "onnx.yaml", self._onnx_case_document(repo=repo_dir, env_script=env_script, case_ids=["onnx_case"]))
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(
                    [
                        "run",
                        str(case_file),
                        "--output-root",
                        tmp_dir,
                        "--config",
                        str(config_file),
                        "--env-profile",
                        "custom_local",
                        "--debug",
                    ]
                )
            self.assertEqual(exit_code, 0)
            run_dirs = [path for path in Path(tmp_dir).iterdir() if path.is_dir() and (path / "summary.json").exists()]
            self.assertEqual(len(run_dirs), 1)
            env_snapshot = json.loads((run_dirs[0] / "env_profile.json").read_text(encoding="utf-8"))
            self.assertEqual(env_snapshot["host"]["mode"], "local")
            self.assertEqual(env_snapshot["metadata"]["profile_name"], "custom_local")

    def test_export_pipeline_graph_cli_writes_dot_and_pdf(self) -> None:
        bootstrap()
        with tempfile.TemporaryDirectory() as tmp_dir:
            repo_dir, _ = self._create_git_resource_repo(Path(tmp_dir))
            env_script = self._create_fake_atc_env(Path(tmp_dir))
            case_file = self._write_case_file(
                Path(tmp_dir),
                "onnx.yaml",
                self._onnx_case_document(repo=repo_dir, env_script=env_script, case_ids=["onnx_case"]),
            )
            export_dir = Path(tmp_dir) / "exports"
            buffer = StringIO()
            with redirect_stdout(buffer):
                exit_code = main(
                    [
                        "export-pipeline-graph",
                        str(case_file),
                        "--output-dir",
                        str(export_dir),
                        "--json",
                    ]
                )
            self.assertEqual(exit_code, 0)
            payload = json.loads(buffer.getvalue())
            dot_path = Path(payload["dot_path"])
            pdf_path = Path(payload["pdf_path"])
            self.assertTrue(dot_path.exists())
            self.assertTrue(pdf_path.exists())
            dot_text = dot_path.read_text(encoding="utf-8")
            self.assertIn("OnnxGitAtcPipeline", dot_text)
            self.assertIn("rankdir=TB", dot_text)
            self.assertIn("Ascend310P3", dot_text)
            self.assertIn("INPUT", dot_text)
            self.assertIn("PARAMS", dot_text)
            self.assertIn("compileModelNode", dot_text)
            self.assertNotIn("resource_ref", dot_text)
            self.assertNotIn("atc_options", dot_text)
            self.assertNotIn("<pipeline:atc_options>", dot_text)
            self.assertIn("output_name: model.om", dot_text)
            self.assertNotIn("COMMANDS", dot_text)


if __name__ == "__main__":
    unittest.main()
