pipeline:
  name: OnnxGitAtcPipeline
  nodes:
    fetchModelNode:
      repo: https://github.com/wybgit/onnx-layer.git
      branch: Abs
      path: Abs_testcase_5a6b43
      model_pattern: "*.onnx"
    compileModelNode:
      env_script: /home/wyb/Ascend/cann-8.5.0/set_env.sh
      soc_version: Ascend310P3
cases:
  - case_id: onnx_git_atc_case
    description: 验证从Git仓获取ONNX并成功完成ATC转换
    level: P0
    expected:
      om_path:
        exists: true
